name: Keep Supabase Alive
on:
  schedule:
    - cron: '0 8 */3 * *'
  workflow_dispatch:
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase
        run: |
          curl -s "${{ secrets.https://tfradfxljdfcjenpuoxt.supabase.co }}/rest/v1/" \
            -H "apikey: ${{ secrets.sb_publishable_z4Wy19-QK_0YKtsJtEhkHA_US4PL8TM }}" \
            -H "Authorization: Bearer ${{ secrets.sb_publishable_z4Wy19-QK_0YKtsJtEhkHA_US4PL8TM }}"
